(mod_item name: (identifier) @name) @declaration.module
(struct_item name: (type_identifier) @name) @declaration.struct
(enum_item name: (type_identifier) @name) @declaration.enum
(trait_item name: (type_identifier) @name) @declaration.trait
(type_item name: (type_identifier) @name) @declaration.type
(function_item name: (identifier) @name) @declaration.function
(function_signature_item name: (identifier) @name) @declaration.method
(const_item name: (identifier) @name) @declaration.constant
(static_item name: (identifier) @name) @declaration.static
(macro_definition name: (identifier) @name) @declaration.macro
(enum_variant name: (identifier) @name) @declaration.variant
(field_declaration name: (field_identifier) @name) @declaration.field
(union_item name: (type_identifier) @name) @declaration.union
