import assert from 'node:assert/strict';
import { after, test } from 'node:test';
import { mkdir, mkdtemp, rm, writeFile, access } from 'node:fs/promises';
import path from 'node:path';
import { tmpdir } from 'node:os';
import { indexRepository } from '../src/pipeline/index.js';
import { resolveConfig, type ApplicationInput } from '../src/core/config.js';
import { AnalysisCache } from '../src/pipeline/cache.js';
import { canonicalJson } from '../src/history/fingerprint.js';
import type { SoftwareGraph } from '../src/core/graph.js';
import { nuxtPath } from '../src/analysis/frameworks/nuxt-path.js';
import { nuxtName } from '../src/analysis/frameworks/nuxt-conventions.js';
import { matchRoutePattern } from '../src/analysis/routes/contracts.js';
import { GraphStore } from '../src/storage/sqlite.js';
import { ProjectionService } from '../src/projection/service.js';
import { nuxtFetchPath } from '../src/analyzers/ts-http.js';

const temporary: string[] = [];
after(async () => { await Promise.all(temporary.map(root => rm(root, { recursive: true, force: true }))); });
async function repository(files: Record<string, string>): Promise<string> { const root = await mkdtemp(path.join(tmpdir(), 'codiluce-nuxt-')); temporary.push(root); for (const [file, text] of Object.entries({ 'package.json': '{"dependencies":{"nuxt":"^4.6.0"}}', ...files })) { await mkdir(path.dirname(path.join(root, file)), { recursive: true }); await writeFile(path.join(root, file), text); } return root; }
async function index(root: string, cache?: AnalysisCache, revision?: string, applications: ApplicationInput[] = [{ name: 'app', path: '.', frameworks: ['nuxt', 'vue'] }]) { return indexRepository(root, { config: await resolveConfig(root, { repository: { name: 'nuxt' }, applications }), cache, revision }); }
const stored = (graph: SoftwareGraph) => canonicalJson({ entities: graph.entities, relations: graph.relations, diagnostics: graph.diagnostics.filter(item => !['git-metrics', 'indexer'].includes(item.analyzer) && item.code !== 'git-ignore-unavailable') });
const pages = (graph: SoftwareGraph) => graph.entities.filter(item => item.type === 'route' && item.metadata.framework === 'nuxt');
const endpoints = (graph: SoftwareGraph) => graph.entities.filter(item => item.type === 'api_endpoint' && item.metadata.framework === 'nuxt');
const component = (graph: SoftwareGraph, file: string) => graph.entities.find(item => item.type === 'component' && item.path === file)!;
const named = (graph: SoftwareGraph, name: string) => graph.entities.find(item => item.name === name)!;

test('Nuxt 4 auto-components, nested pages, layouts and original event-to-server flow preserve UTF-16/CRLF lines', async () => {
  const root = await repository({ 'nuxt.config.ts': 'export default defineNuxtConfig({});', 'app/app.vue': '<template><NuxtLayout><NuxtPage/></NuxtLayout></template>', 'app/pages/users.vue': '<template><NuxtPage/></template>', 'app/pages/users/[id].vue': '<template>😀<BaseFooButton/></template>', 'app/components/base/foo/Button.vue': '<script setup>\r\nfunction save(){return $fetch("/api/users/one",{method:"POST"});}\r\n</script>\r\n<template><button @click="save"/></template>', 'app/layouts/default.vue': '<template><main><slot/></main></template>', 'server/api/users/[id].post.ts': 'export default defineEventHandler(\n(event)=>({id:event.context.params.id}));' });
  const graph = await index(root), page = pages(graph).find(item => item.name === '/users/[id]')!, view = component(graph, 'app/pages/users/[id].vue'), button = component(graph, 'app/components/base/foo/Button.vue'); assert.ok(page); assert.equal(view.metadata.profile, 'vue-3');
  const targets = graph.relations.filter(item => item.from === page.id && item.type === 'routes_to'); assert.equal(targets.length, 4); assert.ok(targets.some(item => item.to === component(graph, 'app/pages/users.vue').id)); assert.ok(targets.some(item => item.to === component(graph, 'app/layouts/default.vue').id));
  const render = graph.relations.find(item => item.from === view.id && item.to === button.id && item.type === 'renders')!; assert.equal(render.evidence[0]!.line, 1); assert.match(render.evidence[0]!.explanation!, /Nuxt indexed component convention/);
  const endpoint = endpoints(graph)[0]!; assert.equal(endpoint.name, 'POST /api/users/[id]'); assert.equal(endpoint.sourceRange!.startLine, 2); const handler = graph.entities.find(item => item.id === graph.relations.find(item => item.from === endpoint.id && item.type === 'handles')!.to)!; assert.equal(handler.path, 'server/api/users/[id].post.ts'); assert.equal(handler.sourceRange!.startLine, 2);
  const event = graph.entities.find(item => item.metadata.vueTemplateEvent)!; assert.equal(event.sourceRange!.startLine, 4); assert.ok(graph.relations.some(item => item.from === event.id && item.to === endpoint.id && item.type === 'requests')); assert.equal(named(graph, 'save').sourceRange!.startLine, 2); assert.equal(named(graph, 'save').metadata.executionContext, 'unknown'); assert.equal(graph.entities.some(item => item.path?.includes('.__codiluce_') || item.path?.startsWith('.nuxt/')), false);
});

test('Nuxt 3 source/server defaults, compatibility 4, explicit directories and aliases use indexed files', async () => {
  const root = await repository({ 'package.json': '{"dependencies":{"nuxt":"^3.21.11"}}', 'nuxt.config.ts': 'import {defineNuxtConfig as config} from "nuxt/config";const opts={srcDir:"website",dir:{pages:"screens",layouts:"shells"},app:{baseURL:"/docs/"},alias:{"custom":"./website/components"}};export default config(opts);', 'website/screens/index.vue': '<script setup>import Card from "custom/Card.vue";</script><template><Card/></template>', 'website/screens/[id].vue': '<script setup>const result=useFetch("/api/info");</script><template><span/></template>', 'website/components/Card.vue': '<template><span/></template>', 'website/server/api/info.get.ts': 'export default (event)=>({ok:true});', 'server/api/wrong.get.ts': 'export default ()=>"wrong";' });
  const graph = await index(root); assert.deepEqual(pages(graph).map(item => item.name).sort(), ['/docs/', '/docs/[id]']); assert.deepEqual(endpoints(graph).map(item => item.name), ['GET /docs/api/info']); assert.ok(graph.relations.some(item => item.type === 'renders' && item.to === component(graph, 'website/components/Card.vue').id)); assert.ok(graph.relations.some(item => item.type === 'requests' && item.to === endpoints(graph)[0]!.id));
  const v4 = await repository({ 'package.json': '{"dependencies":{"nuxt":"^3.21.11"}}', 'nuxt.config.ts': 'export default defineNuxtConfig({future:{compatibilityVersion:4}});', 'app/pages/index.vue': '<template><span/></template>', 'server/api/test.ts': 'export default ()=>"ok";' }); assert.equal(pages(await index(v4)).length, 1); assert.equal(endpoints(await index(v4))[0]!.name, 'ALL /api/test');
});

test('Component naming, custom pathPrefix, prefix, lazy and virtual imports bind original identities', async () => {
  assert.equal(nuxtName('base/foo/FooButton.vue'), 'BaseFooButton'); assert.equal(nuxtName('Item/Item/Item.vue'), 'Item'); assert.equal(nuxtName('some-folder/index.vue', false), 'SomeFolder');
  const root = await repository({ 'nuxt.config.ts': 'export default defineNuxtConfig({components:[{path:"~/widgets",pathPrefix:false,prefix:"Ui"}]});', 'app/pages/index.vue': '<script setup>import {UiButton as Alias} from "#components";import {useFetch as load} from "#imports";const result=load("/api");</script><template><UiButton/><ui-button/><LazyUiButton/><Alias/></template>', 'app/widgets/nested/Button.vue': '<template><span/></template>', 'app/components/Ignored.vue': '<template><span/></template>', 'server/routes/api.ts': 'export default ()=>"ok";' });
  const graph = await index(root), renders = graph.relations.filter(item => item.type === 'renders' && item.from === component(graph, 'app/pages/index.vue').id); assert.equal(renders.length, 1); assert.equal(renders[0]!.evidence.length, 4); assert.equal(renders[0]!.to, component(graph, 'app/widgets/nested/Button.vue').id); assert.ok(graph.relations.some(item => item.type === 'requests')); assert.equal(graph.diagnostics.some(item => item.code === 'unresolved-import' && /#(?:imports|components)/.test(item.reason)), false);
});

test('Lexical/type-only/explicit/mutated component bindings and loop variables suppress auto-import guesses', async () => {
  const root = await repository({ 'app/pages/index.vue': '<script setup>import type Card from "../components/Card.vue";import Other from "../components/Other.vue";let Changed=Other;Changed=unavailable;</script><template><Card/><Changed/><section v-for="Other in values"><Other/></section><Other/></template>', 'app/components/Card.vue': '<template><span/></template>', 'app/components/Other.vue': '<template><span/></template>', 'app/components/Changed.vue': '<template><span/></template>' });
  const graph = await index(root), renders = graph.relations.filter(item => item.type === 'renders' && item.from === component(graph, 'app/pages/index.vue').id); assert.equal(renders.length, 1); assert.equal(renders[0]!.to, component(graph, 'app/components/Other.vue').id); assert.equal(renders[0]!.evidence.length, 1);
});

test('Duplicate component names and client/server/island modes retain gaps without guessing precedence', async () => {
  const root = await repository({ 'app/pages/index.vue': '<template><FooBar/><Thing/></template>', 'app/components/foo/Bar.vue': '<template><span/></template>', 'app/components/FooBar.vue': '<template><span/></template>', 'app/components/Thing.client.vue': '<template><span/></template>', 'app/components/Thing.server.vue': '<template><span/></template>' });
  const graph = await index(root); assert.equal(graph.relations.some(item => item.type === 'renders'), false); assert.ok(graph.diagnostics.some(item => item.code === 'nuxt-component-collision')); assert.ok(graph.diagnostics.some(item => item.code === 'nuxt-component-mode-gap'));
});

test('Server default callbacks, imported aliases, reexports, groups and ANY methods retain source proof and H3 1 semantics', async () => {
  const root = await repository({ 'server/api/(private)/[id].get.ts': 'import {eventHandler as handler} from "h3";import {get} from "../../helpers";export default handler(get);', 'server/api/[id].ts': 'export {all as default} from "../helpers";', 'server/helpers.ts': 'export function get(){return "get";} export const all=()=>"all";', 'server/routes/[...path].ts': 'export default (event)=>"rest";', 'server/routes/trace.trace.ts': 'export default ()=>"trace";' });
  const graph = await index(root); assert.deepEqual(endpoints(graph).map(item => item.name).sort(), ['ALL /[...path]', 'ALL /api/[id]', 'GET /api/[id]', 'TRACE /trace']); assert.equal(endpoints(graph).some(item => item.name.startsWith('HEAD')), false); const all = named(graph, 'ALL /api/[id]'); assert.deepEqual((all.metadata.routing as any).excludedMethods, ['GET']); assert.ok(graph.relations.some(item => item.from === named(graph, 'GET /api/[id]').id && item.to === named(graph, 'get').id && item.type === 'handles'));
});

test('Constrained/invalid/type-only/default handler candidates remain visible and prevent false confirmed matches', async () => {
  const root = await repository({ 'app/pages/index.vue': '<script setup>const data=useFetch("/api/a");const b=useFetch("/api/b");</script><template><span/></template>', 'server/api/a.get.ts': 'export default unknownFactory();', 'server/api/a.ts': 'export default ()=>"fallback";', 'server/api/b.get.ts': 'export type {get as default} from "../helper";', 'server/api/alias.get.ts': 'import {get} from "../helper";let mutable=get;mutable=other;export default mutable;', 'server/helper.ts': 'export function get(){return "ok";}' });
  const graph = await index(root); assert.equal(endpoints(graph).length, 4); assert.equal(graph.relations.some(item => item.type === 'requests'), false); assert.ok(graph.diagnostics.some(item => item.code === 'nuxt-handler-gap')); assert.ok(endpoints(graph).filter(item => item.name !== 'ALL /api/a').every(item => item.metadata.constraintsUnresolved));
});

test('Dynamic/shadowed/escaped/malformed configuration and unsupported versions cannot invent defaults or run target code', async () => {
  const fixtures = [ 'import fs from "node:fs";fs.writeFileSync("EXECUTED","bad");export default factory();', 'function defineNuxtConfig(x){return x;}export default defineNuxtConfig({});', 'const config={};mutate(config);export default config;', 'export default defineNuxtConfig({extends:["../layer"]});', 'export default defineNuxtConfig({srcDir:dynamic});', 'export default defineNuxtConfig({$production:{srcDir:"other"}});', 'export default defineNuxtConfig({ broken: });' ];
  for (const text of fixtures) { const root = await repository({ 'nuxt.config.ts': text, 'app/pages/index.vue': '<template><Card/></template>', 'app/components/Card.vue': '<template><span/></template>', 'server/api/index.ts': 'export default ()=>"ok";' }); const graph = await index(root); assert.equal(pages(graph).length + endpoints(graph).length, 0); assert.equal(graph.relations.some(item => item.type === 'renders'), false); await assert.rejects(access(path.join(root, 'EXECUTED'))); assert.ok(graph.diagnostics.some(item => item.code === 'nuxt-config-gap')); }
  for (const version of ['^2.0.0', '^3.0.0', '^4.0.0']) { const root = await repository({ 'package.json': JSON.stringify({ dependencies: { nuxt: version } }), 'pages/index.vue': '<template><span/></template>' }); const graph = await index(root); assert.equal(pages(graph).length, 0); assert.ok(graph.diagnostics.some(item => item.code === 'nuxt-version-profile')); }
});

test('Unknown modules, layers, plugins, route rules and server middleware preserve constrained registrations', async () => {
  const root = await repository({ 'nuxt.config.ts': 'export default defineNuxtConfig({modules:["custom"],routeRules:{"/api/**":{proxy:"https://elsewhere"}}});', 'layers/theme/nuxt.config.ts': 'throw Error("must not run");export default {};', 'app/plugins/runtime.ts': 'export default defineNuxtPlugin(()=>{});', 'app/pages/index.vue': '<template><Card/></template>', 'app/components/Card.vue': '<template><span/></template>', 'server/middleware/01.auth.ts': 'import {defineEventHandler} from "h3";export default defineEventHandler(()=>{});', 'server/middleware/02.log.ts': 'export default ()=>{};', 'server/api/index.ts': 'export default defineEventHandler(()=>"ok");' });
  const graph = await index(root); assert.ok(pages(graph)[0]!.metadata.constraintsUnresolved); assert.ok(endpoints(graph)[0]!.metadata.constraintsUnresolved); assert.equal((endpoints(graph)[0]!.metadata.routing as any).middleware.length, 2); assert.equal(graph.relations.some(item => item.type === 'renders'), false); assert.ok(graph.diagnostics.some(item => item.code === 'nuxt-middleware-gap'));
});

test('Nuxt page layout meta, false layouts, literal path overrides and outlet boundaries remain explicit', async () => {
  const root = await repository({ 'app/app.vue': '<template><NuxtLayout><NuxtPage/></NuxtLayout></template>', 'app/pages/parent.vue': '<script setup>definePageMeta({layout:"admin"});</script><template><NuxtPage/></template>', 'app/pages/parent/child.vue': '<template><span/></template>', 'app/pages/other.vue': '<script setup>definePageMeta({layout:false,path:"/renamed"});</script><template><span/></template>', 'app/pages/blocked.vue': '<template><span/></template>', 'app/pages/blocked/child.vue': '<template><span/></template>', 'app/layouts/admin.vue': '<template><slot/></template>', 'app/layouts/default.vue': '<template><slot/></template>' });
  const graph = await index(root), child = named(graph, '/parent/child'), other = named(graph, '/renamed'); assert.ok(graph.relations.some(item => item.from === child.id && item.to === component(graph, 'app/layouts/admin.vue').id)); assert.equal(graph.relations.some(item => item.from === other.id && item.to === component(graph, 'app/layouts/default.vue').id), false); assert.ok(named(graph, '/blocked/child').metadata.constraintsUnresolved);
});

test('Empty nested page records are intentional; missing layout slots and server islands retain render boundaries', async () => {
  const root = await repository({ 'app/pages/users.vue': '<template><NuxtPage/></template>', 'app/pages/users/index.vue': '<template><Thing/><Server/></template>', 'app/components/Thing.vue': '<template><span/></template>', 'app/components/Thing.client.vue': '<template><span/></template>', 'app/components/Server.server.vue': '<script setup>function save(){return $fetch("/api");}</script><template><button @click="save"/></template>', 'app/layouts/default.vue': '<template><slot name="other"/></template>', 'server/routes/api.ts': 'export default ()=>"ok";' }); const graph = await index(root); assert.equal(graph.relations.some(item => item.type === 'renders'), false); assert.equal(graph.entities.some(item => item.metadata.vueTemplateEvent), false); assert.ok(pages(graph).every(item => (item.metadata.conditions as string[]).some(reason => reason.includes('default slot')))); assert.equal(graph.diagnostics.some(item => item.code === 'nuxt-route-gap' && item.reason.includes('Duplicate filesystem')), false); assert.equal(component(graph, 'app/components/Server.server.vue').metadata.executionContext, 'server');
});

test('Filesystem page/server patterns distinguish optional, rest, suffix, groups and unsupported Nitro shapes', () => {
  for (const [file, url, yes] of [['(group)/users/[[id]].vue', '/users', true], ['(group)/users/[[id]].vue', '/users/one', true], ['users/[id]-edit.vue', '/users/one-edit', true], ['users/[id]-edit.vue', '/users/one', false], ['[...slug].vue', '/', true]] as const) assert.equal(matchRoutePattern(nuxtPath(file)!, url), yes);
  assert.equal(nuxtPath('users/[id]-edit.get.ts', '', true)!.status, 'partial'); assert.equal(nuxtPath('users/[[id]].get.ts', '', true)!.status, 'partial'); assert.equal(nuxtPath('data.d.ts', '', true), undefined); assert.equal(nuxtPath('-draft.vue'), undefined); assert.equal(nuxtPath('index.server.vue')!.status, 'partial');
  assert.equal(matchRoutePattern(nuxtPath('users/[...path].ts', '', true)!, '/users'), false); assert.equal(matchRoutePattern(nuxtPath('users/[...path].ts', '', true)!, '/users/one'), true); assert.equal(matchRoutePattern(nuxtPath('[...path].ts', '', true)!, '/'), true); assert.equal(matchRoutePattern(nuxtPath('users/[id].ts', '', true)!, '/users//one'), false);
  assert.equal(nuxtFetchPath('/', '/docs'), '/docs'); assert.equal(nuxtFetchPath('/api', '/docs'), '/docs/api'); assert.equal(nuxtFetchPath('/docs/api', '/docs'), '/docs/api'); assert.equal(nuxtFetchPath('https://api.example/api', '/docs'), 'https://api.example/api');
});

test('Local auto-import exports and virtual module mappings cannot impersonate Nuxt preset APIs/components', async () => {
  const root = await repository({ 'package.json': '{"dependencies":{"nuxt":"^4.6.0"},"imports":{"#imports":"./fake.ts","#components":"./fake.ts"}}', 'fake.ts': 'export function useFetch(){return "fake";} export const Card="not a component";', 'app/composables/useFetch.ts': 'export default function useFetch(){return "custom";}', 'app/pages/index.vue': '<script setup>import {useFetch as fake} from "#imports";import {Card as Alias} from "#components";const a=useFetch("/api");const b=fake("/api");</script><template><Alias/></template>', 'app/components/Card.vue': '<template><span/></template>', 'server/routes/api.ts': 'export default ()=>"ok";', 'server/utils/handler.ts': 'export function defineEventHandler(fn){return fn;}', 'server/api/false.get.ts': 'export default defineEventHandler(()=>"unproven");' }); const graph = await index(root); assert.equal(graph.relations.some(item => item.type === 'requests' || item.type === 'renders'), false); assert.ok(named(graph, 'GET /api/false').metadata.constraintsUnresolved); assert.ok(graph.diagnostics.some(item => item.code === 'nuxt-auto-import-gap'));
  const correct = await repository({ 'app/composables/helper.ts': 'export function helper(){return useFetch("/api");}', 'app/pages/index.vue': '<script setup>const data=useFetch("/api");</script><template><span/></template>', 'server/routes/api.ts': 'export default ()=>"ok";' }); assert.ok((await index(correct)).relations.some(item => item.type === 'requests'));
});

test('Mutated framework and generated-module imports cannot qualify handlers, components or fetch transports', async () => {
  const root = await repository({ 'server/api/test.ts': 'import * as H3 from "h3";const alias=H3;alias.defineEventHandler=custom;export default H3.defineEventHandler(()=>"not proven");', 'server/api/forward.ts': 'import {wrap} from "../binding";export default wrap(()=>"not proven");', 'server/binding.ts': 'import * as H3 from "h3";H3.defineEventHandler=custom;export const wrap=H3.defineEventHandler;', 'app/pages/index.vue': '<script setup>import {useFetch} from "#imports";import {Card} from "#components";useFetch=custom;Card=custom;const data=useFetch("/api/test");</script><template><Card/></template>', 'app/components/Card.vue': '<template><span/></template>' }); const graph = await index(root); assert.ok(endpoints(graph).every(item => item.metadata.constraintsUnresolved)); assert.equal(graph.relations.some(item => item.type === 'renders' || item.type === 'requests'), false);
});

test('Malformed server registrations, environment suffixes, disabled server globals and pure-template global writes stay constrained', async () => {
  const root = await repository({ 'app/pages/index.vue': '<script setup>const data=useFetch("/api/a");</script><template><span/></template>', 'server/api/a.get.ts': 'export default (event)=>{const bad=;return "bad";};', 'server/api/a.ts': 'export default ()=>"fallback";', 'server/api/env.get.prod.ts': 'export default ()=>"prod";', 'server/api/env.get.dev.ts': 'export default ()=>"dev";' }); const graph = await index(root); assert.equal(endpoints(graph).length, 4); assert.ok(named(graph, 'GET /api/a').metadata.constraintsUnresolved); assert.equal(graph.relations.some(item => item.type === 'requests'), false); assert.ok(endpoints(graph).filter(item => item.name === 'GET /api/env').every(item => item.metadata.constraintsUnresolved));
  const disabled = await repository({ 'nuxt.config.ts': 'export default defineNuxtConfig({experimental:{nitroAutoImports:false}});', 'server/api/test.ts': 'export default defineEventHandler(()=>"unproven");' }); assert.ok(endpoints(await index(disabled))[0]!.metadata.constraintsUnresolved);
  const pure = await repository({ 'app/pages/index.vue': '<template><button @click="$fetch(\'/api\')"/></template>', 'app/helper.ts': 'globalThis["$fetch"]=custom;', 'server/routes/api.ts': 'export default ()=>"ok";' }); assert.equal((await index(pure)).relations.some(item => item.type === 'requests'), false);
});

test('Same-origin Nuxt transport does not guess a competing application and browser fetch uses configured proxies', async () => {
  const root = await repository({ 'package.json': '{"workspaces":["a","b"]}', 'a/package.json': '{"dependencies":{"nuxt":"^4.6.0"}}', 'a/app/pages/index.vue': '<script setup>function save(){return $fetch("/api");} function native(){return fetch("/remote");}</script><template><button @click="save"/><button @click="native"/></template>', 'a/server/routes/api.ts': 'export default ()=>"a";', 'b/package.json': '{"dependencies":{"nuxt":"^3.21.11"}}', 'b/server/routes/api.ts': 'export default ()=>"b";', 'b/server/routes/remote.ts': 'export default ()=>"remote";' });
  const applications: ApplicationInput[] = [{ name: 'a', path: 'a', frameworks: ['nuxt'], apiProxies: [{ pathPrefix: '/remote', target: 'b' }] }, { name: 'b', path: 'b', frameworks: ['nuxt'] }], graph = await index(root, undefined, undefined, applications), a = endpoints(graph).find(item => item.path === 'a/server/routes/api.ts')!, b = endpoints(graph).find(item => item.path === 'b/server/routes/api.ts')!, remote = endpoints(graph).find(item => item.path === 'b/server/routes/remote.ts')!;
  assert.ok(graph.relations.some(item => item.type === 'requests' && item.to === a.id)); assert.equal(graph.relations.some(item => item.type === 'requests' && item.to === b.id), false); assert.ok(graph.relations.some(item => item.type === 'requests' && item.to === remote.id && item.metadata?.resolution === 'configured-proxy'));
});

test('Fetch globals/imports are binding-qualified; custom options, missing exports and application contexts retain gaps', async () => {
  const root = await repository({ 'app/pages/index.vue': '<script setup>function a($fetch){return $fetch("/api");}function b(){return $fetch("/api",{baseURL:dynamic});}function c(){return fetch("/api");}function d(){return $fetch("/api");}</script><template><button @click="$fetch(\'/api\')"/></template>', 'app/pages/imports.vue': '<script setup>import {$fetch} from "nuxt/app";import {definePageMeta as meta} from "#imports";meta({path:"/wrong"});function invalid(){return $fetch("/api");}</script><template><span/></template>', 'server/api/private.ts': 'import {useFetch} from "nuxt/app";export default ()=>useFetch("/api");', 'server/routes/api.ts': 'export default ()=>"ok";' }); const graph = await index(root); assert.ok(graph.relations.filter(item => item.type === 'requests').length >= 2); assert.equal(graph.relations.some(item => item.from === named(graph, 'a').id && item.type === 'requests'), false); assert.equal(graph.relations.some(item => item.from === named(graph, 'b').id && item.type === 'requests'), false); assert.equal(graph.relations.some(item => item.from === named(graph, 'c').id && item.type === 'requests'), false); assert.equal(graph.relations.some(item => item.from === named(graph, 'invalid').id && item.type === 'requests'), false); assert.ok(pages(graph).some(item => item.name === '/imports')); assert.equal(pages(graph).some(item => item.name === '/wrong'), false); assert.ok(graph.diagnostics.some(item => item.code === 'unresolved-http-call' && item.reason.includes('application-context')));
  const mutated = await repository({ 'app/pages/index.vue': '<script setup>globalThis.$fetch=custom;function save(){return $fetch("/api");}</script><template><button @click="$fetch(\'/api\')"/></template>', 'server/routes/api.ts': 'export default ()=>"ok";' }); assert.equal((await index(mutated)).relations.some(item => item.type === 'requests'), false);
});

test('Vue without Nuxt still has components; pages/components/imports and alternate server builder switches are respected', async () => {
  const root = await repository({ 'nuxt.config.ts': 'export default defineNuxtConfig({pages:false,components:false,imports:{autoImport:false},server:{builder:"vite"}});', 'app/pages/index.vue': '<script setup>import Card from "../components/Card.vue";const data=useFetch("/api");</script><template><Card/></template>', 'app/components/Card.vue': '<template><span/></template>', 'server/routes/api.ts': 'export default ()=>"ok";' }); const graph = await index(root); assert.equal(pages(graph).length + endpoints(graph).length, 0); assert.ok(graph.relations.some(item => item.type === 'renders')); assert.equal(graph.relations.some(item => item.type === 'requests'), false); assert.ok(graph.diagnostics.some(item => item.code === 'nuxt-server-profile-gap'));
  const vue = await repository({ 'package.json': '{"dependencies":{"vue":"^3.0.0"}}', 'pages/index.vue': '<script setup>import Card from "../Card.vue";</script><template><Card/></template>', 'Card.vue': '<template><span/></template>' }); const normal = await index(vue); assert.equal(pages(normal).length, 0); assert.ok(normal.relations.some(item => item.type === 'renders'));
});

test('Connected source and config mutations invalidate cold/warm/revision caches with stable original identities', async () => {
  const root = await repository({ 'nuxt.config.ts': 'export default defineNuxtConfig({});', 'app/pages/index.vue': '<template><Card/></template>', 'app/components/Card.vue': '<script setup>function save(){return $fetch("/api");}</script><template><button @click="save"/></template>', 'server/routes/api.ts': 'export default ()=>"ok";' });
  const cache = new AnalysisCache(path.join(root, '.cache')), first = await index(root, cache), warm = await index(root, cache), revision = await index(root, cache, 'revision'); assert.equal(stored(first), stored(warm)); assert.equal(stored(first), stored(revision));
  await writeFile(path.join(root, 'nuxt.config.ts'), 'export default defineNuxtConfig({app:{baseURL:"/docs"}});'); const changed = await index(root, cache); assert.equal(named(changed, 'GET /api')?.type, undefined); assert.ok(named(changed, 'ALL /docs/api')); assert.equal(stored(changed), stored(await index(root)));
  await writeFile(path.join(root, 'app/components/Card.vue'), '<template><span/></template>'); const removed = await index(root, cache); assert.equal(removed.relations.some(item => item.type === 'requests'), false); assert.equal(component(first, 'app/components/Card.vue').id, component(removed, 'app/components/Card.vue').id); assert.equal(stored(removed), stored(await index(root)));
  const endpoint = endpoints(removed)[0]!, handlerId = removed.relations.find(item => item.from === endpoint.id && item.type === 'handles')!.to;
  await writeFile(path.join(root, 'server/routes/api.ts'), '\n// source moves without changing its declaration\nexport default ()=>"ok";'); const shifted = await index(root, cache); assert.equal(endpoints(shifted)[0]!.id, endpoint.id); assert.equal(shifted.relations.find(item => item.from === endpoint.id && item.type === 'handles')!.to, handlerId); assert.equal(shifted.entities.find(item => item.id === handlerId)!.sourceRange!.startLine, 3); assert.equal(stored(shifted), stored(await index(root)));
});

test('Projection flow and request inspector traverse nested page to auto-component to original Nuxt endpoint evidence', async () => {
  const root = await repository({ 'app/pages/users/[id].vue': '<template><Card/></template>', 'app/components/Card.vue': '<script setup>function save(){return $fetch("/api");}</script><template><button @click="save"/></template>', 'server/routes/api.ts': 'export default ()=>"ok";' }); const graph = await index(root), store = new GraphStore(':memory:');
  try { store.save(graph); const projection = new ProjectionService(store, { root }), endpoint = endpoints(graph)[0]!, page = pages(graph)[0]!, event = graph.entities.find(item => item.metadata.vueTemplateEvent)!; assert.ok(projection.flows({ entity: endpoint.id }).items.some(item => item.entry.id === page.id)); const flows = projection.requestFlows({ entity: event.id }); assert.ok(flows.items.length); const detail = await projection.requestFlow(flows.items[0]!.id, { maxFileBytes: 1 << 20 }); assert.equal(detail.stages.handler, true); assert.match(JSON.stringify(detail), /server\/routes\/api.ts/); } finally { store.close(); }
});
