// Flow overlay storage: `<state>/flows.db`, apart from the graph cache.
// The graph cache (archipelago.db) is regenerated by every index and can be
// deleted at any time; flows are what people authored, so they live in their
// own database and refer to entities by ID only. A step whose entity is gone
// after reindexing stays in the flow and is flagged by the visualizer.
//
// Every save increments a flow's `revision`; an update based on an older
// revision is refused (another tab or person changed it meanwhile).
import { randomUUID } from 'node:crypto';
import { DatabaseSync } from 'node:sqlite';
import { flowSteps, validateFlow, type FlowInput, type StoredFlow } from '../core/flows.js';

export const FLOWS_DATABASE = 'flows.db';
const FLOWS_SCHEMA_VERSION = 1;
const DDL = `
CREATE TABLE flows (
  id TEXT PRIMARY KEY, repository_id TEXT NOT NULL, name TEXT NOT NULL,
  type TEXT NOT NULL CHECK(type IN ('declared', 'static')),
  created_at TEXT NOT NULL, updated_at TEXT NOT NULL, revision INTEGER NOT NULL
) STRICT;
CREATE INDEX flows_repository ON flows(repository_id);
CREATE TABLE flow_steps (
  flow_id TEXT NOT NULL REFERENCES flows(id) ON DELETE CASCADE, position INTEGER NOT NULL,
  entity_id TEXT NOT NULL, relation_id TEXT, PRIMARY KEY (flow_id, position)
) STRICT, WITHOUT ROWID;
CREATE INDEX flow_steps_entity ON flow_steps(entity_id);
PRAGMA user_version = ${FLOWS_SCHEMA_VERSION};
`;
export class FlowError extends Error { constructor(readonly status: number, message: string, readonly flow?: StoredFlow) { super(message); } }
type Row = Record<string, unknown>;

export class FlowStore {
  readonly db: DatabaseSync;
  /** A read-only store over a file that holds no flow tables yet. */
  private empty = false;
  constructor(file: string, private readonly now: () => string = () => new Date().toISOString(), readonly readOnly = false) {
    this.db = new DatabaseSync(file, { readOnly });
    try {
      this.db.exec('PRAGMA foreign_keys = ON; PRAGMA busy_timeout = 5000;');
      if (file !== ':memory:' && !readOnly) this.db.exec('PRAGMA journal_mode = WAL;');
      const version = Number(this.db.prepare('PRAGMA user_version').get()!.user_version);
      if (version === 0 && !readOnly) { this.db.exec('BEGIN IMMEDIATE'); try { this.db.exec(DDL); this.db.exec('COMMIT'); } catch (error) { this.db.exec('ROLLBACK'); throw error; } }
      else if (version === 0) this.empty = true;
      else if (version !== FLOWS_SCHEMA_VERSION) throw new Error(`Unsupported flows schema version ${version}; expected ${FLOWS_SCHEMA_VERSION}`);
    } catch (error) { this.db.close(); throw error; }
  }
  close(): void { this.db.close(); }
  private decode(row: Row): StoredFlow {
    const steps = this.db.prepare('SELECT entity_id, relation_id FROM flow_steps WHERE flow_id=? ORDER BY position').all(String(row.id)).map(step => ({ entityId: String(step.entity_id), ...(step.relation_id ? { relationId: String(step.relation_id) } : {}) }));
    return { id: String(row.id), name: String(row.name), type: row.type as StoredFlow['type'], steps, createdAt: String(row.created_at), updatedAt: String(row.updated_at), revision: Number(row.revision) };
  }
  list(repositoryId: string): StoredFlow[] {
    if (this.empty) return [];
    return this.db.prepare('SELECT * FROM flows WHERE repository_id=? ORDER BY created_at, id').all(repositoryId).map(row => this.decode(row));
  }
  get(repositoryId: string, id: string): StoredFlow | undefined {
    if (this.empty) return undefined;
    const row = this.db.prepare('SELECT * FROM flows WHERE repository_id=? AND id=?').get(repositoryId, id);
    return row ? this.decode(row) : undefined;
  }
  private transaction<T>(work: () => T): T {
    if (this.readOnly) throw new FlowError(403, 'The flow store is read-only');
    this.db.exec('BEGIN IMMEDIATE');
    try { const result = work(); this.db.exec('COMMIT'); return result; } catch (error) { this.db.exec('ROLLBACK'); throw error; }
  }
  private writeSteps(id: string, input: FlowInput): void {
    this.db.prepare('DELETE FROM flow_steps WHERE flow_id=?').run(id);
    const insert = this.db.prepare('INSERT INTO flow_steps VALUES (?, ?, ?, ?)');
    flowSteps(input.steps).forEach((step, position) => insert.run(id, position, step.entityId, step.relationId ?? null));
  }
  create(repositoryId: string, input: unknown, options: { createdAt?: string; updatedAt?: string } = {}): StoredFlow {
    return this.transaction(() => {
      const existing = this.names(repositoryId);
      const problem = validateFlow(input, existing);
      if (problem) throw new FlowError(400, problem);
      const flow = input as FlowInput;
      const id = flow.id ?? randomUUID();
      if (this.db.prepare('SELECT 1 FROM flows WHERE id=?').get(id)) throw new FlowError(409, 'A flow with this id already exists');
      const now = this.now();
      this.db.prepare('INSERT INTO flows VALUES (?, ?, ?, ?, ?, ?, 1)').run(id, repositoryId, flow.name.trim(), flow.type, options.createdAt ?? now, options.updatedAt ?? now);
      this.writeSteps(id, flow);
      return this.get(repositoryId, id)!;
    });
  }
  /** Replace a flow's name, type and steps. `revision` must be the one the edit started from. */
  update(repositoryId: string, id: string, input: unknown, revision: unknown): StoredFlow {
    return this.transaction(() => {
      const current = this.get(repositoryId, id);
      if (!current) throw new FlowError(404, 'Unknown flow');
      if (!Number.isSafeInteger(revision)) throw new FlowError(400, 'revision is required');
      if (revision !== current.revision) throw new FlowError(409, 'The flow was changed elsewhere since it was loaded', current);
      const problem = validateFlow({ ...(input as object), id }, this.names(repositoryId), id);
      if (problem) throw new FlowError(400, problem);
      const flow = input as FlowInput;
      this.db.prepare('UPDATE flows SET name=?, type=?, updated_at=?, revision=revision+1 WHERE id=?').run(flow.name.trim(), flow.type, this.now(), id);
      this.writeSteps(id, flow);
      return this.get(repositoryId, id)!;
    });
  }
  remove(repositoryId: string, id: string): boolean {
    return this.transaction(() => Number(this.db.prepare('DELETE FROM flows WHERE repository_id=? AND id=?').run(repositoryId, id).changes) > 0);
  }
  /**
   * Bring in flows kept elsewhere (a browser's local storage): their ids and
   * dates are kept; one already stored is skipped; a name in use gets a suffix.
   */
  import(repositoryId: string, flows: unknown): { imported: StoredFlow[]; skipped: { id?: string; name?: string; reason: string }[] } {
    if (!Array.isArray(flows) || flows.length > 500) throw new FlowError(400, 'flows must be a list of at most 500 flows');
    const imported: StoredFlow[] = [], skipped: { id?: string; name?: string; reason: string }[] = [];
    for (const item of flows as Partial<StoredFlow>[]) {
      const label = { ...(typeof item?.id === 'string' ? { id: item.id } : {}), ...(typeof item?.name === 'string' ? { name: item.name } : {}) };
      if (typeof item?.id === 'string' && this.db.prepare('SELECT 1 FROM flows WHERE id=?').get(item.id)) { skipped.push({ ...label, reason: 'already stored' }); continue; }
      let name = typeof item?.name === 'string' ? item.name.trim() : '';
      const taken = new Set(this.names(repositoryId).map(flow => flow.name.toLowerCase()));
      for (let n = 2; name && taken.has(name.toLowerCase()) && n < 100; n++) name = `${item.name!.trim().slice(0, 70)} (${n})`;
      const dates = (value: unknown) => typeof value === 'string' && !Number.isNaN(Date.parse(value)) ? value : undefined;
      try { imported.push(this.create(repositoryId, { id: item.id, name, type: item.type, steps: item.steps }, { ...(dates(item.createdAt) ? { createdAt: dates(item.createdAt) } : {}), ...(dates(item.updatedAt) ? { updatedAt: dates(item.updatedAt) } : {}) })); }
      catch (error) { skipped.push({ ...label, reason: error instanceof Error ? error.message : String(error) }); }
    }
    return { imported, skipped };
  }
  private names(repositoryId: string): { id: string; name: string }[] {
    return this.db.prepare('SELECT id, name FROM flows WHERE repository_id=?').all(repositoryId).map(row => ({ id: String(row.id), name: String(row.name) }));
  }
}
